#pragma once
#include <cstdint>

// Per-SM lookup tables for the auto-dispatch decisions in glass::nvidia.
// Tell the wrapper primary templates (gemm<>, gemv<>, gemm_batched_1d<>,
// row_strided_*<>) whether to dispatch to cuBLASDx (true) or fall through
// to the SIMT path (false) for a given shape on a given SM.
//
// EDITING POLICY
// --------------
// The hand-curated values below ship as defaults. To regenerate this file
// for your specific machine (recommended for production deployments — small
// shapes are quite SM-dependent), run:
//
//   python bench/autotune.py --sm AUTO --out src/nvidia/tuning_table.cuh
//
// The autotune script measures both backends for the (M,N,K) grid you
// specify, emits one explicit specialization per measured shape, and leaves
// each `cublasdx_wins*<>` primary template (the conservative heuristic) as
// the fallback for unmeasured shapes.
//
// GLASS_TUNING_TABLE_LOCAL — per-build override (round-2)
// -------------------------------------------------------
// If you want to override entries without editing this file (e.g. for a
// per-host build on shared CI infrastructure), compile with:
//   -DGLASS_TUNING_TABLE_LOCAL='"path/to/your_tuning.cuh"'
// The named header is `#include`d at the bottom of this namespace and may
// add specializations for shapes NOT already specialized in the in-tree
// table above. (C++ disallows re-specialization, so to override a shape
// the in-tree table already covers, you must edit this file directly —
// or remove the in-tree entry first.)
//
// THE HEURISTICS
// --------------
// For shapes with no per-SM measurement, each API has its own heuristic
// reflecting its arithmetic intensity:
//
//   gemm:        max(M,N,K) >= 16 AND min(M,N,K) >= 4
//   gemv:        max(M,N)   >= 32             (lower intensity → SIMT scales farther)
//   batched_1d:  BATCH >= 8 AND max(M,N,K) >= 8
//
// Float-only because cuBLASDx's small-shape kernels are tuned for FP32.

namespace _glass_tuning {

// ─── gemm ─────────────────────────────────────────────────────────────────
// Primary template — conservative shape heuristic for unmeasured (M,N,K,SM).
template <uint32_t M, uint32_t N, uint32_t K, uint32_t SM_VAL>
constexpr bool cublasdx_wins() {
    constexpr uint32_t mx = (M > N ? (M > K ? M : K) : (N > K ? N : K));
    constexpr uint32_t mn = (M < N ? (M < K ? M : K) : (N < K ? N : K));
    return mx >= 16 && mn >= 4;
}

// ─── gemv (M×N → M, no K) ─────────────────────────────────────────────────
// GEMV has lower arithmetic intensity per element than GEMM, so SIMT
// competes farther up the size range.
template <uint32_t M, uint32_t N, uint32_t SM_VAL>
constexpr bool cublasdx_wins_gemv() {
    return (M >= 32) || (N >= 32);
}

// ─── gemm_batched_1d (1D-launch SIMT batched + optional cuBLASDx) ────────
// BATCH multiplies effective compute density. RFC starting heuristic.
template <uint32_t M, uint32_t N, uint32_t K, uint32_t BATCH, uint32_t SM_VAL>
constexpr bool cublasdx_wins_batched() {
    constexpr uint32_t mx = (M > N ? (M > K ? M : K) : (N > K ? N : K));
    return (BATCH >= 8) && (mx >= 8);
}

// ─── row_strided_* (delegate to base APIs) ────────────────────────────────
// Packing cost is roughly constant per call so the tipping shape matches
// the unstrided variant. Users may still specialize these directly if their
// strided cases skew differently.
template <uint32_t M, uint32_t N, uint32_t K,
          uint32_t A_RS, uint32_t B_RS, uint32_t SM_VAL>
constexpr bool cublasdx_wins_gemm_strided() {
    return cublasdx_wins<M, N, K, SM_VAL>();
}

template <uint32_t M, uint32_t N, uint32_t ROW_STRIDE, uint32_t SM_VAL>
constexpr bool cublasdx_wins_gemv_strided() {
    return cublasdx_wins_gemv<M, N, SM_VAL>();
}


// The measured sm_120 specializations live in the autotune-generated marker
// block below (regenerated by `bench/tune.py` / `bench/autotune.py --in-tree`).

// ---------------------------------------------------------------------------
// Per-build local override (round-2). Define GLASS_TUNING_TABLE_LOCAL to a
// header path to append specializations for shapes not already covered
// above. Useful for ephemeral / per-host tuning without polluting source.
// See bench/TUNING.md.
// ---------------------------------------------------------------------------
#ifdef GLASS_TUNING_TABLE_LOCAL
#include GLASS_TUNING_TABLE_LOCAL
#endif

// === BEGIN: autotune-generated specializations ===
// Generated by bench/autotune.py at 2026-06-26 23:22:20 EDT
// Host: plancher-omen-26    SM: sm_120

// ─── gemm ─────────────────────────────────────────────────────────
template <> constexpr bool cublasdx_wins< 3,  3,  3, 1200>() { return false; } // simt wins (0.129us vs cublasdx 0.177us, 37.1%)
template <> constexpr bool cublasdx_wins< 4,  4,  4, 1200>() { return false; } // simt wins (0.147us vs cublasdx 0.311us, 111.4%)
template <> constexpr bool cublasdx_wins< 5,  5,  5, 1200>() { return false; } // simt wins (0.135us vs cublasdx 0.194us, 43.5%)
template <> constexpr bool cublasdx_wins< 6,  6,  6, 1200>() { return false; } // simt wins (0.143us vs cublasdx 0.337us, 135.8%)
template <> constexpr bool cublasdx_wins< 7,  7,  7, 1200>() { return false; } // simt wins (0.148us vs cublasdx 0.200us, 35.2%)
template <> constexpr bool cublasdx_wins< 8,  8,  8, 1200>() { return false; } // simt wins (0.147us vs cublasdx 0.251us, 70.6%)
template <> constexpr bool cublasdx_wins<12, 12, 12, 1200>() { return false; } // tie within ±5%
template <> constexpr bool cublasdx_wins<14, 14, 14, 1200>() { return true; } // cublasdx wins (0.502us vs simt 0.539us, 6.8%)
template <> constexpr bool cublasdx_wins<16, 16, 16, 1200>() { return true; } // cublasdx wins (0.331us vs simt 0.526us, 37.1%)
template <> constexpr bool cublasdx_wins<24, 24, 24, 1200>() { return true; } // cublasdx wins (0.652us vs simt 1.577us, 58.6%)
template <> constexpr bool cublasdx_wins<32, 32, 32, 1200>() { return true; } // cublasdx wins (0.805us vs simt 3.068us, 73.8%)
template <> constexpr bool cublasdx_wins<48, 48, 48, 1200>() { return true; } // cublasdx wins (2.026us vs simt 10.459us, 80.6%)
template <> constexpr bool cublasdx_wins<64, 64, 64, 1200>() { return true; } // cublasdx wins (4.184us vs simt 26.365us, 84.1%)

// ─── gemv ─────────────────────────────────────────────────────────
template <> constexpr bool cublasdx_wins_gemv< 3,  3, 1200>() { return false; } // simt wins (0.125us vs cublasdx 0.165us, 31.5%)
template <> constexpr bool cublasdx_wins_gemv< 4,  4, 1200>() { return false; } // simt wins (0.129us vs cublasdx 0.314us, 143.2%)
template <> constexpr bool cublasdx_wins_gemv< 5,  5, 1200>() { return false; } // simt wins (0.133us vs cublasdx 0.182us, 36.1%)
template <> constexpr bool cublasdx_wins_gemv< 6,  6, 1200>() { return false; } // simt wins (0.138us vs cublasdx 0.330us, 138.8%)
template <> constexpr bool cublasdx_wins_gemv< 7,  7, 1200>() { return false; } // simt wins (0.143us vs cublasdx 0.190us, 33.3%)
template <> constexpr bool cublasdx_wins_gemv< 8,  8, 1200>() { return false; } // simt wins (0.168us vs cublasdx 0.298us, 76.7%)
template <> constexpr bool cublasdx_wins_gemv<12, 12, 1200>() { return false; } // simt wins (0.183us vs cublasdx 0.432us, 136.0%)
template <> constexpr bool cublasdx_wins_gemv<14, 14, 1200>() { return false; } // simt wins (0.178us vs cublasdx 0.428us, 140.7%)
template <> constexpr bool cublasdx_wins_gemv<16, 16, 1200>() { return false; } // simt wins (0.188us vs cublasdx 0.389us, 107.7%)
template <> constexpr bool cublasdx_wins_gemv<24, 24, 1200>() { return false; } // simt wins (0.230us vs cublasdx 0.463us, 101.4%)
template <> constexpr bool cublasdx_wins_gemv<32, 32, 1200>() { return false; } // simt wins (0.262us vs cublasdx 0.605us, 130.7%)
template <> constexpr bool cublasdx_wins_gemv<48, 48, 1200>() { return false; } // simt wins (0.348us vs cublasdx 0.894us, 157.3%)
template <> constexpr bool cublasdx_wins_gemv<64, 64, 1200>() { return false; } // simt wins (0.423us vs cublasdx 1.320us, 212.1%)

// ─── gemv_strided ─────────────────────────────────────────────────
template <> constexpr bool cublasdx_wins_gemv_strided< 4,  4,  6, 1200>() { return false; } // tie within ±5%
template <> constexpr bool cublasdx_wins_gemv_strided< 6,  6,  8, 1200>() { return false; } // tie within ±5%
template <> constexpr bool cublasdx_wins_gemv_strided< 8,  8, 10, 1200>() { return false; } // tie within ±5%
template <> constexpr bool cublasdx_wins_gemv_strided<12, 12, 14, 1200>() { return false; } // tie within ±5%
template <> constexpr bool cublasdx_wins_gemv_strided<14, 14, 16, 1200>() { return false; } // tie within ±5%
template <> constexpr bool cublasdx_wins_gemv_strided<16, 16, 18, 1200>() { return false; } // tie within ±5%
template <> constexpr bool cublasdx_wins_gemv_strided<24, 24, 26, 1200>() { return false; } // tie within ±5%
template <> constexpr bool cublasdx_wins_gemv_strided<32, 32, 34, 1200>() { return false; } // tie within ±5%

// ─── gemm_strided ─────────────────────────────────────────────────
template <> constexpr bool cublasdx_wins_gemm_strided< 4,  4,  4,  6,  6, 1200>() { return false; } // tie within ±5%
template <> constexpr bool cublasdx_wins_gemm_strided< 6,  6,  6,  8,  8, 1200>() { return false; } // tie within ±5%
template <> constexpr bool cublasdx_wins_gemm_strided< 8,  8,  8, 10, 10, 1200>() { return false; } // tie within ±5%
template <> constexpr bool cublasdx_wins_gemm_strided<12, 12, 12, 14, 14, 1200>() { return false; } // tie within ±5%
template <> constexpr bool cublasdx_wins_gemm_strided<14, 14, 14, 16, 16, 1200>() { return false; } // simt wins (0.535us vs cublasdx 0.982us, 83.3%)
template <> constexpr bool cublasdx_wins_gemm_strided<16, 16, 16, 18, 18, 1200>() { return false; } // measurement failed → SIMT default
template <> constexpr bool cublasdx_wins_gemm_strided<24, 24, 24, 26, 26, 1200>() { return false; } // measurement failed → SIMT default
template <> constexpr bool cublasdx_wins_gemm_strided<32, 32, 32, 34, 34, 1200>() { return false; } // measurement failed → SIMT default

// ─── gemm_batched_1d ──────────────────────────────────────────────
template <> constexpr bool cublasdx_wins_batched< 4,  4,  4,  4, 1200>() { return false; } // simt wins (0.176us vs cublasdx 0.436us, 147.6%)
template <> constexpr bool cublasdx_wins_batched< 4,  4,  4,  8, 1200>() { return false; } // simt wins (0.213us vs cublasdx 0.520us, 144.1%)
template <> constexpr bool cublasdx_wins_batched< 4,  4,  4, 16, 1200>() { return false; } // simt wins (0.313us vs cublasdx 0.754us, 141.4%)
template <> constexpr bool cublasdx_wins_batched< 4,  4,  4, 32, 1200>() { return false; } // simt wins (0.476us vs cublasdx 0.796us, 67.0%)
template <> constexpr bool cublasdx_wins_batched< 6,  6,  6,  4, 1200>() { return false; } // simt wins (0.226us vs cublasdx 0.498us, 120.5%)
template <> constexpr bool cublasdx_wins_batched< 6,  6,  6,  8, 1200>() { return false; } // simt wins (0.322us vs cublasdx 0.612us, 90.1%)
template <> constexpr bool cublasdx_wins_batched< 6,  6,  6, 16, 1200>() { return false; } // simt wins (0.538us vs cublasdx 0.895us, 66.4%)
template <> constexpr bool cublasdx_wins_batched< 6,  6,  6, 32, 1200>() { return false; } // simt wins (0.896us vs cublasdx 1.194us, 33.2%)
template <> constexpr bool cublasdx_wins_batched< 8,  8,  8,  4, 1200>() { return false; } // simt wins (0.225us vs cublasdx 0.386us, 71.5%)
template <> constexpr bool cublasdx_wins_batched< 8,  8,  8,  8, 1200>() { return false; } // simt wins (0.343us vs cublasdx 0.554us, 61.5%)
template <> constexpr bool cublasdx_wins_batched< 8,  8,  8, 16, 1200>() { return false; } // simt wins (0.604us vs cublasdx 0.929us, 53.8%)
template <> constexpr bool cublasdx_wins_batched< 8,  8,  8, 32, 1200>() { return false; } // simt wins (1.011us vs cublasdx 1.319us, 30.5%)
template <> constexpr bool cublasdx_wins_batched<12, 12, 12,  4, 1200>() { return false; } // simt wins (0.579us vs cublasdx 0.805us, 39.0%)
template <> constexpr bool cublasdx_wins_batched<12, 12, 12,  8, 1200>() { return false; } // simt wins (0.922us vs cublasdx 1.144us, 24.1%)
template <> constexpr bool cublasdx_wins_batched<12, 12, 12, 16, 1200>() { return false; } // simt wins (1.709us vs cublasdx 1.982us, 16.0%)
template <> constexpr bool cublasdx_wins_batched<12, 12, 12, 32, 1200>() { return true; } // cublasdx wins (2.749us vs simt 3.166us, 13.2%)
template <> constexpr bool cublasdx_wins_batched<16, 16, 16,  4, 1200>() { return true; } // cublasdx wins (0.675us vs simt 0.903us, 25.2%)
template <> constexpr bool cublasdx_wins_batched<16, 16, 16,  8, 1200>() { return true; } // cublasdx wins (1.305us vs simt 1.670us, 21.9%)
template <> constexpr bool cublasdx_wins_batched<16, 16, 16, 16, 1200>() { return true; } // cublasdx wins (2.035us vs simt 3.238us, 37.2%)
template <> constexpr bool cublasdx_wins_batched<16, 16, 16, 32, 1200>() { return true; } // cublasdx wins (4.218us vs simt 6.266us, 32.7%)
template <> constexpr bool cublasdx_wins_batched<24, 24, 24,  4, 1200>() { return true; } // cublasdx wins (2.116us vs simt 2.727us, 22.4%)
template <> constexpr bool cublasdx_wins_batched<24, 24, 24,  8, 1200>() { return true; } // cublasdx wins (3.454us vs simt 5.220us, 33.8%)
template <> constexpr bool cublasdx_wins_batched<24, 24, 24, 16, 1200>() { return false; } // measurement failed → SIMT default
template <> constexpr bool cublasdx_wins_batched<24, 24, 24, 32, 1200>() { return false; } // measurement failed → SIMT default
// === END: autotune-generated specializations ===

} // namespace _glass_tuning
