#pragma once
#include <cstdint>

// Per-SM lookup tables for the auto-dispatch decisions in glass::nvidia.
// Tell the wrapper primary templates (gemm<>, gemv<>, gemm_batched_1d<>,
// row_strided_*<>) whether to dispatch to cuBLASDx (true) or fall through
// to the SIMT path (false) for a given shape on a given SM.
//
// EDITING POLICY
// --------------
// The hand-curated values below ship as defaults. To regenerate this file
// for your specific machine (recommended for production deployments — small
// shapes are quite SM-dependent), run:
//
//   python bench/autotune.py --sm AUTO --out src/nvidia/tuning_table.cuh
//
// The autotune script measures both backends for the (M,N,K) grid you
// specify, emits one explicit specialization per measured shape, and leaves
// each `cublasdx_wins*<>` primary template (the conservative heuristic) as
// the fallback for unmeasured shapes.
//
// GLASS_TUNING_TABLE_LOCAL — per-build override (round-2)
// -------------------------------------------------------
// If you want to override entries without editing this file (e.g. for a
// per-host build on shared CI infrastructure), compile with:
//   -DGLASS_TUNING_TABLE_LOCAL='"path/to/your_tuning.cuh"'
// The named header is `#include`d at the bottom of this namespace and may
// add specializations for shapes NOT already specialized in the in-tree
// table above. (C++ disallows re-specialization, so to override a shape
// the in-tree table already covers, you must edit this file directly —
// or remove the in-tree entry first.)
//
// THE HEURISTICS
// --------------
// For shapes with no per-SM measurement, each API has its own heuristic
// reflecting its arithmetic intensity:
//
//   gemm:        max(M,N,K) >= 16 AND min(M,N,K) >= 4
//   gemv:        max(M,N)   >= 32             (lower intensity → SIMT scales farther)
//   batched_1d:  BATCH >= 8 AND max(M,N,K) >= 8
//
// Float-only because cuBLASDx's small-shape kernels are tuned for FP32.

namespace _glass_tuning {

// ─── gemm ─────────────────────────────────────────────────────────────────
// Primary template — conservative shape heuristic for unmeasured (M,N,K,SM).
template <uint32_t M, uint32_t N, uint32_t K, uint32_t SM_VAL>
constexpr bool cublasdx_wins() {
    constexpr uint32_t mx = (M > N ? (M > K ? M : K) : (N > K ? N : K));
    constexpr uint32_t mn = (M < N ? (M < K ? M : K) : (N < K ? N : K));
    return mx >= 16 && mn >= 4;
}

// ─── gemv (M×N → M, no K) ─────────────────────────────────────────────────
// GEMV has lower arithmetic intensity per element than GEMM, so SIMT
// competes farther up the size range.
template <uint32_t M, uint32_t N, uint32_t SM_VAL>
constexpr bool cublasdx_wins_gemv() {
    return (M >= 32) || (N >= 32);
}

// ─── gemm_batched_1d (1D-launch SIMT batched + optional cuBLASDx) ────────
// BATCH multiplies effective compute density. RFC starting heuristic.
template <uint32_t M, uint32_t N, uint32_t K, uint32_t BATCH, uint32_t SM_VAL>
constexpr bool cublasdx_wins_batched() {
    constexpr uint32_t mx = (M > N ? (M > K ? M : K) : (N > K ? N : K));
    return (BATCH >= 8) && (mx >= 8);
}

// ─── row_strided_* (delegate to base APIs) ────────────────────────────────
// Packing cost is roughly constant per call so the tipping shape matches
// the unstrided variant. Users may still specialize these directly if their
// strided cases skew differently.
template <uint32_t M, uint32_t N, uint32_t K,
          uint32_t A_RS, uint32_t B_RS, uint32_t SM_VAL>
constexpr bool cublasdx_wins_gemm_strided() {
    return cublasdx_wins<M, N, K, SM_VAL>();
}

template <uint32_t M, uint32_t N, uint32_t ROW_STRIDE, uint32_t SM_VAL>
constexpr bool cublasdx_wins_gemv_strided() {
    return cublasdx_wins_gemv<M, N, SM_VAL>();
}


// The measured sm_120 specializations live in the autotune-generated marker
// block below (regenerated by `bench/tune.py` / `bench/autotune.py --in-tree`).

// ---------------------------------------------------------------------------
// Per-build local override (round-2). Define GLASS_TUNING_TABLE_LOCAL to a
// header path to append specializations for shapes not already covered
// above. Useful for ephemeral / per-host tuning without polluting source.
// See bench/TUNING.md.
// ---------------------------------------------------------------------------
#ifdef GLASS_TUNING_TABLE_LOCAL
#include GLASS_TUNING_TABLE_LOCAL
#endif

// === BEGIN: autotune-generated specializations ===
// Generated by bench/autotune.py at 2026-08-14 03:18:08 EDT
// Host: plancher-omen-26    SM: sm_120

// ─── gemm ─────────────────────────────────────────────────────────
template <> constexpr bool cublasdx_wins< 3,  3,  3, 1200>() { return false; } // simt wins (0.141us vs cublasdx 0.181us, 28.0%)
template <> constexpr bool cublasdx_wins< 4,  4,  4, 1200>() { return false; } // simt wins (0.145us vs cublasdx 0.316us, 117.8%)
template <> constexpr bool cublasdx_wins< 5,  5,  5, 1200>() { return false; } // simt wins (0.136us vs cublasdx 0.197us, 44.4%)
template <> constexpr bool cublasdx_wins< 6,  6,  6, 1200>() { return false; } // simt wins (0.139us vs cublasdx 0.339us, 143.5%)
template <> constexpr bool cublasdx_wins< 7,  7,  7, 1200>() { return false; } // simt wins (0.147us vs cublasdx 0.203us, 37.7%)
template <> constexpr bool cublasdx_wins< 8,  8,  8, 1200>() { return false; } // simt wins (0.145us vs cublasdx 0.252us, 73.8%)
template <> constexpr bool cublasdx_wins<12, 12, 12, 1200>() { return false; } // simt wins (0.227us vs cublasdx 0.407us, 79.4%)
template <> constexpr bool cublasdx_wins<14, 14, 14, 1200>() { return true; } // cublasdx wins (0.508us vs simt 0.545us, 6.8%)
template <> constexpr bool cublasdx_wins<16, 16, 16, 1200>() { return false; } // simt wins (0.268us vs cublasdx 0.335us, 25.1%)
template <> constexpr bool cublasdx_wins<24, 24, 24, 1200>() { return true; } // cublasdx wins (0.658us vs simt 0.990us, 33.5%)
template <> constexpr bool cublasdx_wins<32, 32, 32, 1200>() { return true; } // cublasdx wins (0.809us vs simt 1.688us, 52.1%)
template <> constexpr bool cublasdx_wins<48, 48, 48, 1200>() { return true; } // cublasdx wins (2.029us vs simt 5.453us, 62.8%)
template <> constexpr bool cublasdx_wins<64, 64, 64, 1200>() { return true; } // cublasdx wins (4.190us vs simt 11.813us, 64.5%)

// ─── gemv ─────────────────────────────────────────────────────────
template <> constexpr bool cublasdx_wins_gemv< 3,  3, 1200>() { return false; } // simt wins (0.118us vs cublasdx 0.167us, 40.6%)
template <> constexpr bool cublasdx_wins_gemv< 4,  4, 1200>() { return false; } // simt wins (0.128us vs cublasdx 0.319us, 149.4%)
template <> constexpr bool cublasdx_wins_gemv< 5,  5, 1200>() { return false; } // simt wins (0.133us vs cublasdx 0.183us, 37.7%)
template <> constexpr bool cublasdx_wins_gemv< 6,  6, 1200>() { return false; } // simt wins (0.135us vs cublasdx 0.332us, 146.7%)
template <> constexpr bool cublasdx_wins_gemv< 7,  7, 1200>() { return false; } // simt wins (0.143us vs cublasdx 0.192us, 34.1%)
template <> constexpr bool cublasdx_wins_gemv< 8,  8, 1200>() { return false; } // simt wins (0.170us vs cublasdx 0.309us, 81.4%)
template <> constexpr bool cublasdx_wins_gemv<12, 12, 1200>() { return false; } // simt wins (0.184us vs cublasdx 0.435us, 136.3%)
template <> constexpr bool cublasdx_wins_gemv<14, 14, 1200>() { return false; } // simt wins (0.197us vs cublasdx 0.432us, 118.7%)
template <> constexpr bool cublasdx_wins_gemv<16, 16, 1200>() { return false; } // simt wins (0.208us vs cublasdx 0.397us, 90.9%)
template <> constexpr bool cublasdx_wins_gemv<24, 24, 1200>() { return false; } // simt wins (0.225us vs cublasdx 0.464us, 106.6%)
template <> constexpr bool cublasdx_wins_gemv<32, 32, 1200>() { return false; } // simt wins (0.261us vs cublasdx 0.610us, 133.6%)
template <> constexpr bool cublasdx_wins_gemv<48, 48, 1200>() { return false; } // simt wins (0.345us vs cublasdx 0.899us, 160.8%)
template <> constexpr bool cublasdx_wins_gemv<64, 64, 1200>() { return false; } // simt wins (0.422us vs cublasdx 1.326us, 214.0%)

// ─── gemv_strided ─────────────────────────────────────────────────
template <> constexpr bool cublasdx_wins_gemv_strided< 4,  4,  6, 1200>() { return false; } // tie within ±5%
template <> constexpr bool cublasdx_wins_gemv_strided< 6,  6,  8, 1200>() { return false; } // tie within ±5%
template <> constexpr bool cublasdx_wins_gemv_strided< 8,  8, 10, 1200>() { return false; } // tie within ±5%
template <> constexpr bool cublasdx_wins_gemv_strided<12, 12, 14, 1200>() { return false; } // tie within ±5%
template <> constexpr bool cublasdx_wins_gemv_strided<14, 14, 16, 1200>() { return false; } // tie within ±5%
template <> constexpr bool cublasdx_wins_gemv_strided<16, 16, 18, 1200>() { return false; } // tie within ±5%
template <> constexpr bool cublasdx_wins_gemv_strided<24, 24, 26, 1200>() { return false; } // tie within ±5%
template <> constexpr bool cublasdx_wins_gemv_strided<32, 32, 34, 1200>() { return false; } // tie within ±5%

// ─── gemm_strided ─────────────────────────────────────────────────
template <> constexpr bool cublasdx_wins_gemm_strided< 4,  4,  4,  6,  6, 1200>() { return false; } // tie within ±5%
template <> constexpr bool cublasdx_wins_gemm_strided< 6,  6,  6,  8,  8, 1200>() { return false; } // tie within ±5%
template <> constexpr bool cublasdx_wins_gemm_strided< 8,  8,  8, 10, 10, 1200>() { return false; } // tie within ±5%
template <> constexpr bool cublasdx_wins_gemm_strided<12, 12, 12, 14, 14, 1200>() { return false; } // tie within ±5%
template <> constexpr bool cublasdx_wins_gemm_strided<14, 14, 14, 16, 16, 1200>() { return false; } // simt wins (0.544us vs cublasdx 0.994us, 82.7%)
template <> constexpr bool cublasdx_wins_gemm_strided<16, 16, 16, 18, 18, 1200>() { return false; } // tie within ±5%
template <> constexpr bool cublasdx_wins_gemm_strided<24, 24, 24, 26, 26, 1200>() { return false; } // measurement failed → SIMT default
template <> constexpr bool cublasdx_wins_gemm_strided<32, 32, 32, 34, 34, 1200>() { return false; } // measurement failed → SIMT default

// ─── gemm_batched_1d ──────────────────────────────────────────────
template <> constexpr bool cublasdx_wins_batched< 4,  4,  4,  4, 1200>() { return false; } // simt wins (0.170us vs cublasdx 0.456us, 168.8%)
template <> constexpr bool cublasdx_wins_batched< 4,  4,  4,  8, 1200>() { return false; } // simt wins (0.242us vs cublasdx 0.545us, 125.7%)
template <> constexpr bool cublasdx_wins_batched< 4,  4,  4, 16, 1200>() { return false; } // simt wins (0.399us vs cublasdx 0.774us, 93.8%)
template <> constexpr bool cublasdx_wins_batched< 4,  4,  4, 32, 1200>() { return false; } // simt wins (0.400us vs cublasdx 0.807us, 101.8%)
template <> constexpr bool cublasdx_wins_batched< 6,  6,  6,  4, 1200>() { return false; } // simt wins (0.222us vs cublasdx 0.515us, 132.3%)
template <> constexpr bool cublasdx_wins_batched< 6,  6,  6,  8, 1200>() { return false; } // simt wins (0.308us vs cublasdx 0.631us, 104.7%)
template <> constexpr bool cublasdx_wins_batched< 6,  6,  6, 16, 1200>() { return false; } // simt wins (0.516us vs cublasdx 0.912us, 76.8%)
template <> constexpr bool cublasdx_wins_batched< 6,  6,  6, 32, 1200>() { return false; } // simt wins (0.843us vs cublasdx 1.204us, 42.8%)
template <> constexpr bool cublasdx_wins_batched< 8,  8,  8,  4, 1200>() { return false; } // simt wins (0.225us vs cublasdx 0.391us, 73.9%)
template <> constexpr bool cublasdx_wins_batched< 8,  8,  8,  8, 1200>() { return false; } // simt wins (0.339us vs cublasdx 0.561us, 65.4%)
template <> constexpr bool cublasdx_wins_batched< 8,  8,  8, 16, 1200>() { return false; } // simt wins (0.583us vs cublasdx 0.940us, 61.3%)
template <> constexpr bool cublasdx_wins_batched< 8,  8,  8, 32, 1200>() { return false; } // simt wins (0.796us vs cublasdx 1.330us, 67.0%)
template <> constexpr bool cublasdx_wins_batched<12, 12, 12,  4, 1200>() { return false; } // simt wins (0.343us vs cublasdx 0.833us, 142.9%)
template <> constexpr bool cublasdx_wins_batched<12, 12, 12,  8, 1200>() { return false; } // simt wins (0.546us vs cublasdx 1.170us, 114.3%)
template <> constexpr bool cublasdx_wins_batched<12, 12, 12, 16, 1200>() { return false; } // simt wins (1.061us vs cublasdx 1.999us, 88.4%)
template <> constexpr bool cublasdx_wins_batched<12, 12, 12, 32, 1200>() { return false; } // simt wins (2.257us vs cublasdx 2.764us, 22.4%)
template <> constexpr bool cublasdx_wins_batched<16, 16, 16,  4, 1200>() { return false; } // simt wins (0.523us vs cublasdx 0.680us, 30.0%)
template <> constexpr bool cublasdx_wins_batched<16, 16, 16,  8, 1200>() { return false; } // simt wins (0.931us vs cublasdx 1.314us, 41.2%)
template <> constexpr bool cublasdx_wins_batched<16, 16, 16, 16, 1200>() { return false; } // tie within ±5%
template <> constexpr bool cublasdx_wins_batched<16, 16, 16, 32, 1200>() { return false; } // measurement failed → SIMT default
template <> constexpr bool cublasdx_wins_batched<24, 24, 24,  4, 1200>() { return false; } // simt wins (1.368us vs cublasdx 2.125us, 55.4%)
template <> constexpr bool cublasdx_wins_batched<24, 24, 24,  8, 1200>() { return false; } // simt wins (2.522us vs cublasdx 3.468us, 37.5%)
template <> constexpr bool cublasdx_wins_batched<24, 24, 24, 16, 1200>() { return false; } // measurement failed → SIMT default
template <> constexpr bool cublasdx_wins_batched<24, 24, 24, 32, 1200>() { return false; } // measurement failed → SIMT default
// === END: autotune-generated specializations ===

} // namespace _glass_tuning
