#!/usr/bin/env python3
"""GLASS autotuner — measure SIMT vs cuBLASDx on this machine for each of the
five auto-dispatch primaries in `_glass_tuning` and emit a per-host overrides
file consumed via `GLASS_TUNING_TABLE_LOCAL`.

Usage:
    python3 bench/autotune.py [--sm AUTO|<sm>]
                              [--apis gemm,gemv,gemv_strided,gemm_strided,gemm_batched_1d]
                              [--iters 10000]
                              [--out PATH]
                              [--margin 0.05]
                              [--dry-run]

Defaults:
    --sm AUTO        — detect via nvidia-smi
    --apis           — all five round-2 primaries
    --iters 10000    — per-kernel timing iterations
    --margin 0.05    — within ±5% counts as a tie; ties default to SIMT
    --out PATH       — bench/tuning/<hostname>.cuh by default. The shipped
                       src/nvidia/tuning_table.cuh is NEVER overwritten by
                       this script — it carries the per-API primary templates
                       and curated specializations and must stay stable.

Consume the per-host output via the round-2 override mechanism:
    nvcc ... -DGLASS_TUNING_TABLE_LOCAL='"bench/tuning/<hostname>.cuh"' ...

Requires MATHDX_ROOT set (cuBLASDx headers needed for the cuBLASDx leg).
"""

import argparse
import concurrent.futures
import datetime
import hashlib
import json
import os
import pathlib
import platform
import re
import subprocess
import sys
import textwrap
import time

import tune_pick as tp  # the one shared tie rule (also used by bench/tune.py)

BENCH_DIR  = pathlib.Path(__file__).parent.resolve()


def _cublasdx_wins(simt, cdx, margin):
    """Shared verdict: cuBLASDx is the dependency impl, so it must clear the
    margin over SIMT. Single source of truth = tune_pick.pick."""
    return tp.pick({"simt": simt, "cublasdx": cdx}, margin, {"cublasdx"}) == "cublasdx"
GLASS_DIR  = BENCH_DIR.parent
TUNING_DIR = BENCH_DIR / "tuning"


# ─── Per-API microbench templates ───────────────────────────────────────────
#
# Each API_CONFIGS entry carries:
#   - shape_keys: tuple of shape-grid parameter names (used for parsing
#                 --shapes and for `microbench.format(**placeholders)`).
#   - default_shapes: list of tuples matching shape_keys.
#   - microbench: textwrap-dedented C++ source with `{key}` placeholders.
#                 Must compile to a binary that prints two lines:
#                     simt     <us_per_op>
#                     cublasdx <us_per_op>
#   - spec_fmt: callable (shape_values..., sms) -> the C++ specialization
#               name (e.g. "cublasdx_wins_gemv<6,6,1200>"). The output
#               file prepends "template <> constexpr bool ", appends "()
#               { return <bool>; }".
#   - label_fmt: callable (shape) -> short human label for progress prints.
#
# To add an API: append an entry to API_CONFIGS; main loop picks it up.

# NOTE: the preamble is concatenated with each per-API microbench template
# and the WHOLE combined string is passed through `str.format(**placeholders)`.
# That means literal `{` / `}` must appear as `{{` / `}}` here (and in every
# microbench template below) so .format leaves them alone.
_BENCH_PREAMBLE = textwrap.dedent("""
    // Auto-generated by bench/autotune.py
    #include <cstdio>
    #include <cstdlib>
    #include <ctime>
    #ifdef GLASS_BENCH_CUBLASDX
    #include <cublasdx.hpp>
    #endif
    #include "../glass-nvidia.cuh"

    static const int TC = 64;

    static double elapsed_us(struct timespec a, struct timespec b) {{
        return (double)(b.tv_sec - a.tv_sec) * 1e6
             + (double)(b.tv_nsec - a.tv_nsec) * 1e-3;
    }}

    // A launched kernel that errors (shared-mem overflow, >1024 threads,
    // cuBLASDx reject) must be reported as a FAILURE, not timed as a silent
    // ~0us. After a launch, leg_failed() syncs, checks the error, and on
    // failure prints a non-numeric marker line so bench/autotune.py records
    // the leg as "measurement failed -> SIMT default" instead of believing a
    // bogus 0.000us. Returns true on failure.
    static bool leg_failed(const char* leg) {{
        cudaError_t e = cudaDeviceSynchronize();
        if (e == cudaSuccess) e = cudaGetLastError();
        if (e != cudaSuccess) {{
            printf("%s FAILED %s\\n", leg, cudaGetErrorString(e));
            return true;
        }}
        return false;
    }}

    // best-of-3 + spread (methodology audit 2026-08-11): the min of 3 timed
    // legs estimates the clean time (noise is one-sided on a quiet GPU); the
    // spread (max/min - 1, %) rides on the output line so autotune.py can
    // flag cells whose jitter exceeds the decision margin.
    #define TIME3(LEG, LAUNCH) do {{ \
        double _best = 1e30, _worst = 0.0; \
        for (int _t = 0; _t < 3; _t++) {{ \
            struct timespec _a, _b; \
            clock_gettime(CLOCK_MONOTONIC, &_a); \
            LAUNCH; cudaDeviceSynchronize(); \
            clock_gettime(CLOCK_MONOTONIC, &_b); \
            double _us = elapsed_us(_a, _b) / iters; \
            if (_us < _best) _best = _us; \
            if (_us > _worst) _worst = _us; \
        }} \
        printf("%s %.6f spread %.1f\\n", LEG, _best, (_worst / _best - 1.0) * 100.0); \
    }} while (0)
""").strip()


# ───── gemm ────────────────────────────────────────────────────────────────
_GEMM_MICROBENCH = _BENCH_PREAMBLE + textwrap.dedent("""

    static const int M = {M}, N = {N}, K = {K};

    namespace glass {{ namespace nvidia {{ namespace block {{   // block:: required since the 2026-07-30 namespace restructure
        DEFINE_NVIDIA_GEMM_BLOCKDIM(M, N, K, TC)
    }}}}}}

    __global__ void k_simt(float* A, float* B, float* C, volatile float* sink, int iters) {{
        for (int rep = 0; rep < iters; rep++) {{
            glass::gemm<float, M, N, K>(1.f, A, B, 0.f, C);
            __syncthreads();
            if (threadIdx.x == 0) sink[rep & 0xFF] = C[0];
            __syncthreads();
        }}
    }}

    __global__ void k_cublasdx(float* A, float* B, float* C, volatile float* sink, int iters) {{
        extern __shared__ __align__(16) char smem[];
        for (int rep = 0; rep < iters; rep++) {{
            glass::nvidia::block::gemm<float, M, N, K, TC>(1.f, A, B, 0.f, C, smem);
            __syncthreads();
            if (threadIdx.x == 0) sink[rep & 0xFF] = C[0];
            __syncthreads();
        }}
    }}

    int main(int argc, char** argv) {{
        int iters = (argc > 1) ? atoi(argv[1]) : 5000;
        float *dA, *dB, *dC, *dSink;
        cudaMalloc(&dA, M*N * sizeof(float));
        cudaMalloc(&dB, N*K * sizeof(float));
        cudaMalloc(&dC, M*K * sizeof(float));
        cudaMalloc(&dSink, 256 * sizeof(float));
        constexpr size_t smem = glass::nvidia::block::gemm_scratch_bytes<float, M, N, K, TC>();

        k_simt<<<1, TC>>>(dA, dB, dC, dSink, 100);
        bool simt_ok = !leg_failed("simt");
        cudaFuncSetAttribute(k_cublasdx, cudaFuncAttributeMaxDynamicSharedMemorySize, smem);
        k_cublasdx<<<1, TC, smem>>>(dA, dB, dC, dSink, 100);
        bool cdx_ok = !leg_failed("cublasdx");

        if (simt_ok) {{
            TIME3("simt", (k_simt<<<1, TC>>>(dA, dB, dC, dSink, iters)));
        }}

        if (cdx_ok) {{
            TIME3("cublasdx", (k_cublasdx<<<1, TC, smem>>>(dA, dB, dC, dSink, iters)));
        }}

        cudaFree(dA); cudaFree(dB); cudaFree(dC); cudaFree(dSink);
        return 0;
    }}
""")


# ───── gemv ────────────────────────────────────────────────────────────────
_GEMV_MICROBENCH = _BENCH_PREAMBLE + textwrap.dedent("""

    static const int M = {M}, N = {N};

    namespace glass {{ namespace nvidia {{ namespace block {{   // block:: required since the 2026-07-30 namespace restructure
        DEFINE_NVIDIA_GEMV_BLOCKDIM(M, N, TC)
    }}}}}}

    __global__ void k_simt(float* A, float* x, float* y, volatile float* sink, int iters) {{
        for (int rep = 0; rep < iters; rep++) {{
            glass::gemv<float, M, N>(1.f, A, x, 0.f, y);
            __syncthreads();
            if (threadIdx.x == 0) sink[rep & 0xFF] = y[0];
            __syncthreads();
        }}
    }}

    __global__ void k_cublasdx(float* A, float* x, float* y, volatile float* sink, int iters) {{
        extern __shared__ __align__(16) char smem[];
        for (int rep = 0; rep < iters; rep++) {{
            glass::nvidia::block::gemv<float, M, N, TC>(1.f, A, x, 0.f, y, smem);
            __syncthreads();
            if (threadIdx.x == 0) sink[rep & 0xFF] = y[0];
            __syncthreads();
        }}
    }}

    int main(int argc, char** argv) {{
        int iters = (argc > 1) ? atoi(argv[1]) : 5000;
        float *dA, *dx, *dy, *dSink;
        cudaMalloc(&dA, M*N * sizeof(float));
        cudaMalloc(&dx, N   * sizeof(float));
        cudaMalloc(&dy, M   * sizeof(float));
        cudaMalloc(&dSink, 256 * sizeof(float));
        constexpr size_t smem = glass::nvidia::block::gemv_scratch_bytes<float, M, N, TC>();

        k_simt<<<1, TC>>>(dA, dx, dy, dSink, 100);
        bool simt_ok = !leg_failed("simt");
        cudaFuncSetAttribute(k_cublasdx, cudaFuncAttributeMaxDynamicSharedMemorySize, smem);
        k_cublasdx<<<1, TC, smem>>>(dA, dx, dy, dSink, 100);
        bool cdx_ok = !leg_failed("cublasdx");

        if (simt_ok) {{
            TIME3("simt", (k_simt<<<1, TC>>>(dA, dx, dy, dSink, iters)));
        }}

        if (cdx_ok) {{
            TIME3("cublasdx", (k_cublasdx<<<1, TC, smem>>>(dA, dx, dy, dSink, iters)));
        }}

        cudaFree(dA); cudaFree(dx); cudaFree(dy); cudaFree(dSink);
        return 0;
    }}
""")


# ───── gemv_strided ─────────────────────────────────────────────────────
# ROW_STRIDE is sized to be > N so the strided pack pass is exercised on the
# cuBLASDx leg. SIMT path is glass::gemv_strided (base SIMT impl).
_ROW_STRIDED_GEMV_MICROBENCH = _BENCH_PREAMBLE + textwrap.dedent("""

    static const int M = {M}, N = {N}, ROW_STRIDE = {ROW_STRIDE};

    namespace glass {{ namespace nvidia {{ namespace block {{   // block:: required since the 2026-07-30 namespace restructure
        DEFINE_NVIDIA_GEMV_BLOCKDIM(M, N, TC)
    }}}}}}

    __global__ void k_simt(float* A, float* x, float* y, volatile float* sink, int iters) {{
        for (int rep = 0; rep < iters; rep++) {{
            glass::gemv_strided<float, M, N, ROW_STRIDE>(1.f, A, x, 0.f, y);
            __syncthreads();
            if (threadIdx.x == 0) sink[rep & 0xFF] = y[0];
            __syncthreads();
        }}
    }}

    __global__ void k_cublasdx(float* A, float* x, float* y, volatile float* sink, int iters) {{
        extern __shared__ __align__(16) char smem[];
        for (int rep = 0; rep < iters; rep++) {{
            glass::nvidia::block::gemv_strided<float, M, N, ROW_STRIDE, TC>(1.f, A, x, 0.f, y, smem);
            __syncthreads();
            if (threadIdx.x == 0) sink[rep & 0xFF] = y[0];
            __syncthreads();
        }}
    }}

    int main(int argc, char** argv) {{
        int iters = (argc > 1) ? atoi(argv[1]) : 5000;
        float *dA, *dx, *dy, *dSink;
        cudaMalloc(&dA, ROW_STRIDE * N * sizeof(float));
        cudaMalloc(&dx, N   * sizeof(float));
        cudaMalloc(&dy, M   * sizeof(float));
        cudaMalloc(&dSink, 256 * sizeof(float));
        constexpr size_t smem =
            glass::nvidia::block::gemv_strided_scratch_bytes<float, M, N, ROW_STRIDE, TC>();

        k_simt<<<1, TC>>>(dA, dx, dy, dSink, 100);
        bool simt_ok = !leg_failed("simt");
        cudaFuncSetAttribute(k_cublasdx, cudaFuncAttributeMaxDynamicSharedMemorySize, smem);
        k_cublasdx<<<1, TC, smem>>>(dA, dx, dy, dSink, 100);
        bool cdx_ok = !leg_failed("cublasdx");

        if (simt_ok) {{
            TIME3("simt", (k_simt<<<1, TC>>>(dA, dx, dy, dSink, iters)));
        }}

        if (cdx_ok) {{
            TIME3("cublasdx", (k_cublasdx<<<1, TC, smem>>>(dA, dx, dy, dSink, iters)));
        }}

        cudaFree(dA); cudaFree(dx); cudaFree(dy); cudaFree(dSink);
        return 0;
    }}
""")


# ───── gemm_strided ─────────────────────────────────────────────────────
# A_RS sized > M; B_RS sized > N. The strided pack pass is exercised on both
# legs (SIMT does it inside ::glass::gemm_strided; cuBLASDx does it inside
# the nvidia wrapper before the cuBLASDx execute).
_ROW_STRIDED_GEMM_MICROBENCH = _BENCH_PREAMBLE + textwrap.dedent("""

    static const int M = {M}, N = {N}, K = {K};
    static const int A_RS = {A_RS}, B_RS = {B_RS};

    namespace glass {{ namespace nvidia {{ namespace block {{   // block:: required since the 2026-07-30 namespace restructure
        DEFINE_NVIDIA_GEMM_BLOCKDIM(M, N, K, TC)
    }}}}}}

    __global__ void k_simt(float* A, float* B, float* C, volatile float* sink, int iters) {{
        for (int rep = 0; rep < iters; rep++) {{
            glass::gemm_strided<float, M, N, K, A_RS, B_RS>(1.f, A, B, 0.f, C);
            __syncthreads();
            if (threadIdx.x == 0) sink[rep & 0xFF] = C[0];
            __syncthreads();
        }}
    }}

    __global__ void k_cublasdx(float* A, float* B, float* C, volatile float* sink, int iters) {{
        extern __shared__ __align__(16) char smem[];
        for (int rep = 0; rep < iters; rep++) {{
            glass::nvidia::block::gemm_strided<float, M, N, K, A_RS, B_RS, TC>(1.f, A, B, 0.f, C, smem);
            __syncthreads();
            if (threadIdx.x == 0) sink[rep & 0xFF] = C[0];
            __syncthreads();
        }}
    }}

    int main(int argc, char** argv) {{
        int iters = (argc > 1) ? atoi(argv[1]) : 5000;
        float *dA, *dB, *dC, *dSink;
        cudaMalloc(&dA, A_RS * N * sizeof(float));
        cudaMalloc(&dB, B_RS * K * sizeof(float));
        cudaMalloc(&dC, M    * K * sizeof(float));
        cudaMalloc(&dSink, 256 * sizeof(float));
        constexpr size_t smem =
            glass::nvidia::block::gemm_strided_scratch_bytes<float, M, N, K, A_RS, B_RS, TC>();

        k_simt<<<1, TC>>>(dA, dB, dC, dSink, 100);
        bool simt_ok = !leg_failed("simt");
        cudaFuncSetAttribute(k_cublasdx, cudaFuncAttributeMaxDynamicSharedMemorySize, smem);
        k_cublasdx<<<1, TC, smem>>>(dA, dB, dC, dSink, 100);
        bool cdx_ok = !leg_failed("cublasdx");

        if (simt_ok) {{
            TIME3("simt", (k_simt<<<1, TC>>>(dA, dB, dC, dSink, iters)));
        }}

        if (cdx_ok) {{
            TIME3("cublasdx", (k_cublasdx<<<1, TC, smem>>>(dA, dB, dC, dSink, iters)));
        }}

        cudaFree(dA); cudaFree(dB); cudaFree(dC); cudaFree(dSink);
        return 0;
    }}
""")


# ───── gemm_batched_1d ──────────────────────────────────────────────────────
# Compares the 1D SIMT batched (glass::nvidia::block::gemm_batched_1d) against
# the 2D cuBLASDx batched (glass::nvidia::block::gemm_batched). The launches differ
# (1D = TC*BATCH threads; 2D = dim3(TC, BATCH)). The autotune still picks the
# faster wall-time per op — that's what cublasdx_wins_batched<> answers.
_GEMM_BATCHED_MICROBENCH = _BENCH_PREAMBLE + textwrap.dedent("""

    static const int M = {M}, N = {N}, K = {K};
    static const int BATCH = {BATCH};
    // Cap threads-per-matrix so the 2D launch dim3(BTC, BATCH) and the 1D
    // launch BTC*BATCH stay within the 1024-thread/block limit. The default
    // TC=64 with BATCH=32 would request 2048 threads, so the launch fails
    // silently — recorded as a bogus 0.000us before this cap + leg_failed().
    static const int BTC = (TC * BATCH > 1024) ? (1024 / BATCH) : TC;

    namespace glass {{ namespace nvidia {{ namespace block {{   // block:: required since the 2026-07-30 namespace restructure
        DEFINE_NVIDIA_GEMM_BLOCKDIM(M, N, K, BTC)
        DEFINE_NVIDIA_GEMM_BATCHED_BLOCKDIM(M, N, K, BATCH, BTC)
    }}}}}}

    __global__ void k_simt(float** As, float** Bs, float** Cs, volatile float* sink, int iters) {{
        for (int rep = 0; rep < iters; rep++) {{
            glass::nvidia::block::gemm_batched_1d<float, M, N, K, BATCH, BTC>(
                1.f, As, Bs, 0.f, Cs);
            __syncthreads();
            if (threadIdx.x == 0) sink[rep & 0xFF] = Cs[0][0];
            __syncthreads();
        }}
    }}

    __global__ void k_cublasdx(float** As, float** Bs, float** Cs,
                                volatile float* sink, int iters) {{
        extern __shared__ __align__(16) char smem[];
        for (int rep = 0; rep < iters; rep++) {{
            glass::nvidia::block::gemm_batched<float, M, N, K, BATCH, BTC>(
                1.f, As, Bs, 0.f, Cs, smem);
            __syncthreads();
            if (threadIdx.x == 0 && threadIdx.y == 0) sink[rep & 0xFF] = Cs[0][0];
            __syncthreads();
        }}
    }}

    int main(int argc, char** argv) {{
        int iters = (argc > 1) ? atoi(argv[1]) : 5000;
        float *dA, *dB, *dC, *dSink;
        // SIMT batched_1d expects contiguous A/B/C arrays of BATCH*(MxN/NxK/MxK).
        cudaMalloc(&dA, BATCH * M * N * sizeof(float));
        cudaMalloc(&dB, BATCH * N * K * sizeof(float));
        cudaMalloc(&dC, BATCH * M * K * sizeof(float));
        cudaMalloc(&dSink, 256 * sizeof(float));

        // cuBLASDx gemm_batched takes ptr-arrays; build them by indexing into
        // the same contiguous buffers above.
        float **dAs, **dBs, **dCs;
        cudaMalloc(&dAs, BATCH * sizeof(float*));
        cudaMalloc(&dBs, BATCH * sizeof(float*));
        cudaMalloc(&dCs, BATCH * sizeof(float*));
        float *hAs[BATCH], *hBs[BATCH], *hCs[BATCH];
        for (int b = 0; b < BATCH; b++) {{
            hAs[b] = dA + b * M * N;
            hBs[b] = dB + b * N * K;
            hCs[b] = dC + b * M * K;
        }}
        cudaMemcpy(dAs, hAs, BATCH * sizeof(float*), cudaMemcpyHostToDevice);
        cudaMemcpy(dBs, hBs, BATCH * sizeof(float*), cudaMemcpyHostToDevice);
        cudaMemcpy(dCs, hCs, BATCH * sizeof(float*), cudaMemcpyHostToDevice);
        constexpr size_t smem =
            glass::nvidia::block::gemm_batched_scratch_bytes<float, M, N, K, BATCH, BTC>();

        // SIMT batched_1d launches 1D with BTC*BATCH threads, ptr-array args.
        k_simt<<<1, BTC * BATCH>>>(dAs, dBs, dCs, dSink, 100);
        bool simt_ok = !leg_failed("simt");
        // cuBLASDx batched launches 2D dim3(BTC, BATCH).
        cudaFuncSetAttribute(k_cublasdx, cudaFuncAttributeMaxDynamicSharedMemorySize, smem);
        k_cublasdx<<<1, dim3(BTC, BATCH), smem>>>(dAs, dBs, dCs, dSink, 100);
        bool cdx_ok = !leg_failed("cublasdx");

        if (simt_ok) {{
            TIME3("simt", (k_simt<<<1, BTC * BATCH>>>(dAs, dBs, dCs, dSink, iters)));
        }}

        if (cdx_ok) {{
            TIME3("cublasdx", (k_cublasdx<<<1, dim3(BTC, BATCH), smem>>>(dAs, dBs, dCs, dSink, iters)));
        }}

        cudaFree(dA); cudaFree(dB); cudaFree(dC); cudaFree(dSink);
        cudaFree(dAs); cudaFree(dBs); cudaFree(dCs);
        return 0;
    }}
""")


# ─── Per-API config: shape grid + template + specialization formatter ─────

_SQUARE = [3, 4, 5, 6, 7, 8, 12, 14, 16, 24, 32, 48, 64]


def _spec_gemm(m, n, k, sms):
    return f"cublasdx_wins<{m:>2},{n:>3},{k:>3},{sms:>5}>"


def _spec_gemv(m, n, sms):
    return f"cublasdx_wins_gemv<{m:>2},{n:>3},{sms:>5}>"


def _spec_gemv_strided(m, n, rs, sms):
    return f"cublasdx_wins_gemv_strided<{m:>2},{n:>3},{rs:>3},{sms:>5}>"


def _spec_gemm_strided(m, n, k, a_rs, b_rs, sms):
    return (f"cublasdx_wins_gemm_strided<"
            f"{m:>2},{n:>3},{k:>3},{a_rs:>3},{b_rs:>3},{sms:>5}>")


def _spec_batched(m, n, k, batch, sms):
    return f"cublasdx_wins_batched<{m:>2},{n:>3},{k:>3},{batch:>3},{sms:>5}>"


API_CONFIGS = {
    "gemm": {
        "shape_keys": ("M", "N", "K"),
        "default_shapes": [(m, m, m) for m in _SQUARE],
        "microbench": _GEMM_MICROBENCH,
        "spec_fmt": _spec_gemm,
        "label_fmt": lambda s: f"{s[0]}x{s[1]}x{s[2]}",
    },
    "gemv": {
        "shape_keys": ("M", "N"),
        "default_shapes": [(m, m) for m in _SQUARE],
        "microbench": _GEMV_MICROBENCH,
        "spec_fmt": _spec_gemv,
        "label_fmt": lambda s: f"{s[0]}x{s[1]}",
    },
    "gemv_strided": {
        "shape_keys": ("M", "N", "ROW_STRIDE"),
        # Stride a few elements wider than N to exercise the pack pass.
        "default_shapes": [(m, m, m + 2) for m in (4, 6, 8, 12, 14, 16, 24, 32)],
        "microbench": _ROW_STRIDED_GEMV_MICROBENCH,
        "spec_fmt": _spec_gemv_strided,
        "label_fmt": lambda s: f"{s[0]}x{s[1]} rs={s[2]}",
    },
    "gemm_strided": {
        "shape_keys": ("M", "N", "K", "A_RS", "B_RS"),
        "default_shapes": [(m, m, m, m + 2, m + 2)
                           for m in (4, 6, 8, 12, 14, 16, 24, 32)],
        "microbench": _ROW_STRIDED_GEMM_MICROBENCH,
        "spec_fmt": _spec_gemm_strided,
        "label_fmt": lambda s: f"{s[0]}x{s[1]}x{s[2]} A_rs={s[3]} B_rs={s[4]}",
    },
    "gemm_batched_1d": {
        "shape_keys": ("M", "N", "K", "BATCH"),
        # (square, batch) cross product, kept modest because every (M,N,K,BATCH)
        # is a separate cuBLASDx compile.
        "default_shapes": [(m, m, m, b)
                           for m in (4, 6, 8, 12, 16, 24)
                           for b in (4, 8, 16, 32)],
        "microbench": _GEMM_BATCHED_MICROBENCH,
        "spec_fmt": _spec_batched,
        "label_fmt": lambda s: f"{s[0]}x{s[1]}x{s[2]} B={s[3]}",
    },
}


def parse_shapes_for_api(api, spec):
    """Parse '--shapes' for one API. Accepts ';' separated tuples; tuple arity
    must match shape_keys length."""
    keys = API_CONFIGS[api]["shape_keys"]
    out = []
    for part in spec.split(";"):
        part = part.strip()
        if not part:
            continue
        vals = tuple(int(x) for x in part.split(","))
        if len(vals) != len(keys):
            raise ValueError(
                f"--shapes entry '{part}' has arity {len(vals)} but API "
                f"'{api}' expects {len(keys)} values: {keys}")
        out.append(vals)
    return out


# ─── Compile + run one (api, shape) ─────────────────────────────────────────

def detect_sm() -> int:
    out = subprocess.check_output(
        ["nvidia-smi", "--query-gpu=compute_cap", "--format=csv,noheader"],
        text=True, stderr=subprocess.DEVNULL,
    ).strip().split("\n")[0].strip()
    major, minor = out.split(".")
    return int(f"{major}{minor}0")


# Quiet-GPU discipline and provenance stamps are shared across the four
# benchmark drivers — one copy in bench_common (they drifted as four copies;
# this file's provenance block had diverged into a "key: value" format).
from bench_common import (compute_pids, require_quiet_gpu as wait_for_quiet_gpu,
                          watch_process)
import bench_common


def provenance(sms, margin):
    return bench_common.provenance(
        "autotune", f"arch=sm_{sms // 10} decision_margin={margin:.6f}")


_LIB_DIGEST = None


def lib_digest():
    """Content hash of the whole header-only library (glass*.cuh + src/**/*.cuh),
    so any library edit busts every cached microbench binary. Computed once."""
    global _LIB_DIGEST
    if _LIB_DIGEST is None:
        h = hashlib.sha256()
        files = sorted(GLASS_DIR.glob("glass*.cuh")) + sorted((GLASS_DIR / "src").rglob("*.cuh"))
        for f in files:
            h.update(f.read_bytes())
        _LIB_DIGEST = h.hexdigest()
    return _LIB_DIGEST


def build_shape(api, shape, sms, mathdx_root, build_dir):
    """Compile one (api, shape) microbench into the persistent build cache.

    Hash-keyed on the rendered source + the library digest + the SM, so a cached
    binary is reused across runs and a stale one (lib/source/SM change) rebuilds.
    A compile that cuBLASDx rejects (e.g. BlockDim too small) is remembered via a
    ``.fail`` marker so prebuild doesn't keep retrying it. Returns
    ``(bin_path_or_None, status)`` where status ∈ {cached, built, cached-fail, fail}.
    """
    cfg = API_CONFIGS[api]
    placeholders = dict(zip(cfg["shape_keys"], shape))
    label = "_".join(f"{k}{v}" for k, v in placeholders.items())
    src = cfg["microbench"].format(**placeholders)
    key = hashlib.sha256((src + lib_digest() + f"sm{sms}").encode()).hexdigest()[:12]
    bin_path = build_dir / f"{api}_{label}_{key}"
    fail_path = build_dir / f"{api}_{label}_{key}.fail"
    if bin_path.exists():
        return bin_path, "cached"
    if fail_path.exists():
        return None, "cached-fail"
    src_path = build_dir / f"{api}_{label}.cu"
    src_path.write_text(src)
    cmd = [
        "nvcc", "-std=c++17", f"-arch=sm_{sms // 10}", "-O3",
        f"-I{GLASS_DIR}", f"-I{GLASS_DIR / 'src'}",
        f"-I{mathdx_root / 'include'}",
        f"-I{mathdx_root / 'external' / 'cutlass' / 'include'}",
        "-DGLASS_BENCH_CUBLASDX", f"-DGLASS_TARGET_SM={sms}",
        "--expt-relaxed-constexpr", "-Xptxas", "-O1",
        "-o", str(bin_path), str(src_path),
    ]
    res = subprocess.run(cmd, capture_output=True, text=True)
    if res.returncode != 0:
        fail_path.write_text((res.stderr or "")[:1000])
        return None, "fail"
    return bin_path, "built"


def measure_shape(api, shape, sms, iters, mathdx_root, build_dir,
                  baseline=frozenset()):
    cfg = API_CONFIGS[api]
    bin_path, status = build_shape(api, shape, sms, mathdx_root, build_dir)
    if bin_path is None:
        # cuBLASDx may reject some shapes outright → "SIMT wins by default".
        print(f"    [{api} {cfg['label_fmt'](shape)}] compile failed → SIMT default",
              file=sys.stderr)
        return None, None, None, None

    proc = subprocess.Popen([str(bin_path), str(iters)], stdout=subprocess.PIPE,
                            stderr=subprocess.PIPE, text=True)
    _, foreign = watch_process(proc, baseline, poll_s=0.5)
    stdout, stderr = proc.communicate()
    if foreign:
        sys.exit(f"timing invalidated by foreign compute PIDs: {sorted(foreign)}")
    if proc.returncode != 0:
        print(f"    [{api} {cfg['label_fmt'](shape)}] runtime failure: "
              f"{stderr[:200]}", file=sys.stderr)
        return None, None, None, None

    simt_us = cublasdx_us = None
    simt_spread = cublasdx_spread = None
    for line in stdout.splitlines():
        m1 = re.match(r"^(simt|cublasdx)\s+([\d.]+)(?:\s+spread\s+([\d.]+))?",
                      line.strip())
        if not m1:
            continue
        if m1.group(1) == "simt":
            simt_us = float(m1.group(2))
            simt_spread = float(m1.group(3)) if m1.group(3) is not None else None
        else:
            cublasdx_us = float(m1.group(2))
            cublasdx_spread = float(m1.group(3)) if m1.group(3) is not None else None
        # audit hook: a cell whose 3-trial spread exceeds the decision margin
        # cannot cleanly resolve it — surface the jitter instead of hiding it.
        if m1.group(3) is not None and float(m1.group(3)) > 5.0:
            print(f"    !! [{api} {cfg['label_fmt'](shape)}] {m1.group(1)} "
                  f"trial spread {m1.group(3)}% > 5% margin — verdict unreliable, "
                  f"re-run on a quieter GPU", file=sys.stderr)
    return simt_us, cublasdx_us, simt_spread, cublasdx_spread


# ─── Emit per-host overrides file ──────────────────────────────────────────

_OUTPUT_HEADER = """// Auto-generated by GLASS bench/autotune.py — do NOT hand-edit.
//
// Per-host tuning overrides. Consumed by src/nvidia/tuning_table.cuh via the
// GLASS_TUNING_TABLE_LOCAL mechanism. The shipped in-tree tuning table carries
// the per-API primary templates + heuristics + curated specializations; this
// file just appends measured specializations for THIS host. Add no namespace
// scopes — the consuming `tuning_table.cuh` includes this inside
// `namespace _glass_tuning { ... }`.
//
// Regenerate with:
//   python3 bench/autotune.py --sm AUTO
// Consume in your build with:
//   nvcc ... -DGLASS_TUNING_TABLE_LOCAL='"@INCLUDE_PATH@"' ...
"""


def emit_overrides(out_path: pathlib.Path,
                   sms: int,
                   results_by_api: dict,
                   margin: float,
                   include_path: str,
                   hostname: str):
    """Results contain shape, timings, and spreads for both contenders.

    Timing and spread values can be None when measurement failed.
    """
    header = _OUTPUT_HEADER.replace("@INCLUDE_PATH@", include_path).rstrip()
    lines = [header, ""]
    lines.append(f"// Host: {hostname}    SM: sm_{sms // 10} (sms={sms})")
    lines.append(f"// Generated at {time.strftime('%Y-%m-%d %H:%M:%S %Z')}")
    lines.append(f"// Tie margin: ±{margin*100:.0f}% (ties default to SIMT)")
    lines.append("")

    total = 0
    for api in API_CONFIGS:
        results = results_by_api.get(api)
        if not results:
            continue
        lines.append(f"// ─── {api} ─" + ("─" * (72 - len(api))))
        cfg = API_CONFIGS[api]
        # Sub-microsecond measurements are unreliable on small kernels (timer
        # granularity, kernel launch failures, shared-mem overflows that
        # bail before the kernel body runs all produce 0.000us-ish values).
        # Below this floor we can't trust either leg, so we conservatively
        # default to SIMT.
        MIN_TRUSTWORTHY_US = 0.05
        for shape, simt, cdx, _simt_spread, _cdx_spread in results:
            spec = cfg["spec_fmt"](*shape, sms)
            if simt is None or cdx is None:
                verdict = "false"
                note = "measurement failed → SIMT default"
            elif simt < MIN_TRUSTWORTHY_US or cdx < MIN_TRUSTWORTHY_US:
                verdict = "false"
                note = (f"measurement below noise floor "
                        f"(simt={simt:.3f}us, cublasdx={cdx:.3f}us; "
                        f"< {MIN_TRUSTWORTHY_US:.2f}us) → SIMT default")
            else:
                ratio = cdx / simt
                if _cublasdx_wins(simt, cdx, margin):
                    verdict = "true"
                    note = (f"cublasdx wins ({cdx:.3f}us vs simt {simt:.3f}us, "
                            f"{(1-ratio)*100:.1f}%)")
                elif ratio > (1.0 + margin):
                    verdict = "false"
                    note = (f"simt wins ({simt:.3f}us vs cublasdx {cdx:.3f}us, "
                            f"{(ratio-1)*100:.1f}%)")
                else:
                    verdict = "false"
                    note = f"tie within ±{margin*100:.0f}% → SIMT default"
            lines.append(f"template <> constexpr bool {spec}() {{ return {verdict}; }} // {note}")
            total += 1
        lines.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines))
    print(f"\nWrote {out_path} ({total} specializations across "
          f"{sum(1 for v in results_by_api.values() if v)} APIs).")


def emit_results_md(md_path: pathlib.Path,
                    sms: int,
                    results_by_api: dict,
                    margin: float,
                    hostname: str,
                    provenance_lines: list[str]):
    lines = [
        f"# autotune results — {hostname}, sm_{sms // 10}",
        "",
        f"_Generated by `bench/autotune.py` at "
        f"{time.strftime('%Y-%m-%d %H:%M:%S %Z')}._",
        "",
        f"Tie tolerance: ±{margin*100:.0f}% (ties default to SIMT).",
        "",
        "## Provenance",
        "",
        *[f"- ``{line}``" for line in provenance_lines],
        "",
    ]
    for api in API_CONFIGS:
        results = results_by_api.get(api)
        if not results:
            continue
        cfg = API_CONFIGS[api]
        keys = cfg["shape_keys"]
        lines.append(f"## {api}")
        lines.append("")
        header = ("| " + " | ".join(keys)
                  + " | SIMT (us) | SIMT spread | cuBLASDx (us) | "
                    "cuBLASDx spread | Winner | Speedup |")
        sep = "|" + "|".join(["---"] * (len(keys) + 6)) + "|"
        lines.extend([header, sep])
        # See emit_overrides_file: sub-noise-floor measurements are
        # untrustworthy and we conservatively default to SIMT.
        MIN_TRUSTWORTHY_US = 0.05
        for shape, simt, cdx, simt_spread, cdx_spread in results:
            shape_cells = " | ".join(str(s) for s in shape)
            if simt is None or cdx is None:
                lines.append(f"| {shape_cells} | — | — | — | — | "
                             "SIMT (compile failed) | — |")
                continue
            ss = "—" if simt_spread is None else f"{simt_spread:.1f}%"
            cs = "—" if cdx_spread is None else f"{cdx_spread:.1f}%"
            if simt < MIN_TRUSTWORTHY_US or cdx < MIN_TRUSTWORTHY_US:
                lines.append(f"| {shape_cells} | {simt:.3f} | {ss} | "
                             f"{cdx:.3f} | {cs} | SIMT (sub-noise) | — |")
                continue
            if _cublasdx_wins(simt, cdx, margin):
                lines.append(f"| {shape_cells} | {simt:.3f} | {ss} | "
                             f"{cdx:.3f} | {cs} | **cuBLASDx** | "
                             f"{simt/cdx:.2f}× |")
            elif simt < cdx * (1.0 - margin):
                lines.append(f"| {shape_cells} | {simt:.3f} | {ss} | "
                             f"{cdx:.3f} | {cs} | **SIMT** | "
                             f"{cdx/simt:.2f}× |")
            else:
                lines.append(f"| {shape_cells} | {simt:.3f} | {ss} | "
                             f"{cdx:.3f} | {cs} | tie (→ SIMT) | — |")
        lines.append("")
    md_path.parent.mkdir(parents=True, exist_ok=True)
    md_path.write_text("\n".join(lines))
    print(f"Wrote {md_path}")


# ─── main ───────────────────────────────────────────────────────────────────

def emit_defaults_table(sweep_path, out_path, sms, margin=0.05):
    """Parse a bench_mega_sweep run (mega_sweep_*.txt) and emit a per-host override
    header for glass-defaults.cuh (native plus NVIDIA block/thread ladder). Uses the NPROB=8192
    throughput regime for f32 + f64."""
    text = pathlib.Path(sweep_path).read_text()
    cells = tp.parse_mega_sweep(text, nprob=8192)
    winners = {}          # (native_only, dtype, op) -> {N: backend}
    for (dtype, op, N), measured in cells.items():
        for native_only in (False, True):
            timings = {name: value for name, value in measured.items()
                       if not native_only or name not in {"nvidia", "nvidia_thread"}}
            winner = tp.pick(timings, margin, {"nvidia", "nvidia_thread"})
            if winner:
                be = "nvidia_block" if winner == "nvidia" else winner
                winners.setdefault((native_only, dtype, op), {})[N] = be
    if not winners:
        sys.exit(f"No NPROB=8192 verdicts parsed from {sweep_path}")

    def emit_op(op, dtype, native_only):
        picks = winners.get((native_only, dtype, op))
        if not picks:
            return None
        ns = sorted(picks)
        runs = []                          # (hi_N, backend) collapsed threshold ranges
        for N in ns:
            be = picks[N]
            if runs and runs[-1][1] == be:
                runs[-1] = (N, be)
            else:
                runs.append((N, be))
        conds = " ".join(f"if (N <= {hi}u) return backend::{be};" for hi, be in runs[:-1])
        return f"{conds} return backend::{runs[-1][1]};".strip()

    # NOTE: included by glass-defaults.cuh INSIDE namespace glass::defaults (via the
    # GLASS_DEFAULTS_TABLE_LOCAL hook), so this fragment must NOT re-open the namespace.
    lines = [
        f"// Generated by bench/autotune.py --emit-defaults from {pathlib.Path(sweep_path).name}",
        f"// (sm {sms}, NPROB=8192 throughput regime). Do not edit by hand.",
        "// Included by glass-defaults.cuh inside namespace glass::defaults — no namespace wrapper.",
        "#define GLASS_DEFAULTS_HAVE_LOCAL",
        "constexpr backend local_ideal(op o, uint32_t N, bool f64, uint32_t /*sm*/,",
        "                              bool allow_nvidia) {",
    ]
    for native_only, dep_guard in ((False, "if (allow_nvidia) {"),
                                   (True, "if (!allow_nvidia) {")):
        lines.append(f"    {dep_guard}")
        for dtype, type_guard in (("f32", "if (!f64) {"),
                                  ("f64", "if (f64) {")):
            lines.append(f"        {type_guard}")
            for op in tp.LADDER_OPS:
                body = emit_op(op, dtype, native_only)
                if body:
                    lines.append(f"            if (o == op::{op}) {{ {body} }}")
            lines.append("        }")
        lines.append("    }")
    lines += ["    return backend::block;", "}", ""]
    out = pathlib.Path(out_path)
    out.write_text("\n".join(lines))
    print(f"==> wrote {out}  ({len(winners)} (dtype,op) groups)")
    print(f"    use via: -DGLASS_DEFAULTS_TABLE_LOCAL='\"{out}\"'")


def main():
    p = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument("--sm", default="AUTO",
                   help="SM number (e.g. 860, 1200) or AUTO (detect via nvidia-smi)")
    p.add_argument("--apis", default=",".join(API_CONFIGS.keys()),
                   help=f"Comma-separated API list. Default: all five. "
                        f"Choices: {', '.join(API_CONFIGS.keys())}")
    p.add_argument("--shapes", default=None,
                   help="Override default shape grid. Format: semicolon-separated "
                        "tuples, where the arity matches each API's parameters. "
                        "Same grid applied to every API named in --apis — to "
                        "give per-API grids, run autotune separately per API.")
    p.add_argument("--iters", type=int, default=10000,
                   help="Per-kernel timed iterations (default 10000). Bump for "
                        "noisy machines or for shapes hitting the tie tolerance.")
    p.add_argument("--out", default=None,
                   help="Output path. Default: bench/tuning/<hostname>.cuh. "
                        "Use --in-tree to write to the shipped src/nvidia/tuning_table.cuh "
                        "(only do this for upstream PRs).")
    p.add_argument("--in-tree", action="store_true",
                   help="(Advanced) Write specializations to "
                        "src/nvidia/tuning_table.cuh, preserving its round-2 primary "
                        "templates and structure. For upstream-PR contributors. The "
                        "default per-host output is the right choice for almost everyone.")
    p.add_argument("--margin", type=float, default=0.05,
                   help="Tie tolerance: |1 - cublasdx/simt| <= margin counts as a "
                        "tie (default 0.05)")
    p.add_argument("--dry-run", action="store_true",
                   help="Measure but don't write any files")
    p.add_argument("--force", action="store_true",
                   help="ignore the initial busy-GPU preflight; foreign compute "
                        "PIDs appearing during a cell still invalidate it")
    p.add_argument("--build-only", action="store_true",
                   help="Compile every microbench into the build cache and exit "
                        "(no timing, no table written). Pre-warms the cache so the "
                        "actual sweep on a quiet GPU is execute-only. Safe to run "
                        "while the GPU is busy — compilation is CPU-bound.")
    p.add_argument("--build-dir", default=None,
                   help="Persistent build cache dir (default "
                        "bench/.tune_cache/sm<sms>). Binaries are hash-keyed on the "
                        "source + library digest + SM and reused across runs.")
    p.add_argument("--build-jobs", type=int, default=1,
                   help="Parallel nvcc compiles for --build-only (default 1). Each "
                        "cuBLASDx compile needs ~6-7GB RAM, so size to free_RAM/7 "
                        "(e.g. 6 on a 64GB box). Ignored outside --build-only; the "
                        "timed sweep always runs serially for clean measurement.")
    p.add_argument("--emit-defaults", metavar="SWEEP_TXT", default=None,
                   help="Parse a bench_mega_sweep run (mega_sweep_*.txt) and emit a per-host "
                        "glass-defaults.cuh override header (native and NVIDIA ladder), then exit.")
    args = p.parse_args()

    sms = detect_sm() if args.sm == "AUTO" else int(args.sm)
    hostname = platform.node().replace(" ", "_")

    if args.emit_defaults:
        out = args.out or str(TUNING_DIR / f"{hostname}_defaults.cuh")
        TUNING_DIR.mkdir(parents=True, exist_ok=True)
        emit_defaults_table(args.emit_defaults, out, sms, args.margin)
        return

    requested_apis = [a.strip() for a in args.apis.split(",") if a.strip()]
    unknown = [a for a in requested_apis if a not in API_CONFIGS]
    if unknown:
        sys.exit(f"Unknown API(s): {unknown}. Choices: {list(API_CONFIGS.keys())}")

    mathdx_root_env = os.environ.get("MATHDX_ROOT")
    if not mathdx_root_env:
        sys.exit("ERROR: MATHDX_ROOT not set — autotune needs cuBLASDx headers.")
    mathdx_root = pathlib.Path(mathdx_root_env)

    build_dir = (pathlib.Path(args.build_dir) if args.build_dir
                 else BENCH_DIR / ".tune_cache" / f"sm{sms}")
    build_dir.mkdir(parents=True, exist_ok=True)

    def shapes_for(api):
        if args.shapes:
            try:
                return parse_shapes_for_api(api, args.shapes)
            except ValueError as e:
                # --shapes arity mismatches this API (common with multiple APIs
                # in --apis); skip rather than abort the whole run.
                print(f"  [skip {api}] {e}", file=sys.stderr)
                return None
        return list(API_CONFIGS[api]["default_shapes"])

    # ── build-only: compile every microbench into the cache, no timing ──
    if args.build_only:
        jobs = max(1, args.build_jobs)
        print(f"Prebuild: sm_{sms // 10}   cache={build_dir}   parallel={jobs}")
        print(f"APIs: {', '.join(requested_apis)}   MATHDX_ROOT={mathdx_root}\n")
        # Building is not timed, so it parallelizes freely (each build_shape just
        # waits on an nvcc subprocess). Distinct shapes write distinct .cu/.bin
        # paths (hash-keyed), so the cache is parallel-safe. The later timed
        # sweep stays serial — only compilation fans out here.
        work = [(api, shape)
                for api in requested_apis
                for shape in (shapes_for(api) or [])]
        tally = {"cached": 0, "built": 0, "fail": 0, "cached-fail": 0}

        def _build(item):
            api, shape = item
            _, status = build_shape(api, shape, sms, mathdx_root, build_dir)
            return api, shape, status

        with concurrent.futures.ThreadPoolExecutor(max_workers=jobs) as ex:
            for api, shape, status in ex.map(_build, work):
                tally[status] = tally.get(status, 0) + 1
                print(f"  {api:16} {API_CONFIGS[api]['label_fmt'](shape):24} {status}",
                      flush=True)
        print(f"\nPrebuilt: {tally['built']} new, {tally['cached']} already cached, "
              f"{tally['fail'] + tally['cached-fail']} cuBLASDx-rejected (SIMT default).")
        print(f"Cache ready at {build_dir} — the timed sweep is now execute-only.")
        return

    wait_for_quiet_gpu(args.force)
    # Under --force, pre-existing PIDs are tolerated by design — subtract them
    # so the mid-run watch only trips on NEW processes.
    baseline = compute_pids() if args.force else frozenset()
    # Snapshot before the first measurement and before --in-tree can mutate a
    # generated header. Previously this was computed after writing the table,
    # so timing_started_utc and source_sha256 described the output tree rather
    # than the source that the cached binaries actually measured.
    run_provenance = provenance(sms, args.margin)

    if args.in_tree:
        out = (GLASS_DIR / "src" / "nvidia" / "tuning_table.cuh").resolve()
    elif args.out is not None:
        out = pathlib.Path(args.out).resolve()
    else:
        out = (TUNING_DIR / f"{hostname}.cuh").resolve()
    md = out.parent / (out.stem + "_results.md")

    print(f"Autotune target: sm_{sms // 10} (sms={sms})  host={hostname}")
    print(f"APIs:            {', '.join(requested_apis)}")
    print(f"Iterations:      {args.iters}")
    print(f"Tie margin:      ±{args.margin*100:.0f}%")
    print(f"MATHDX_ROOT:     {mathdx_root}")
    print(f"Build cache:     {build_dir}")
    print(f"Output:          {out}{' (dry run)' if args.dry_run else ''}")
    if args.in_tree:
        print("                 (--in-tree: writing to shipped tuning_table.cuh; "
              "consider per-host instead)")

    results_by_api: dict[str, list] = {}
    for api in requested_apis:
        cfg = API_CONFIGS[api]
        shapes = shapes_for(api)
        if shapes is None:
            print(f"  → run autotune separately for {api} with matching shape "
                  f"arity {cfg['shape_keys']}.", file=sys.stderr)
            continue
        print(f"\n── {api} ({len(shapes)} shapes) " + "─" * max(0, 60 - len(api)))
        api_results = []
        for shape in shapes:
            label = cfg["label_fmt"](shape)
            print(f"  measuring {label} ...", end=" ", flush=True)
            simt, cdx, simt_spread, cdx_spread = measure_shape(
                api, shape, sms, args.iters, mathdx_root, build_dir, baseline)
            if simt is None and cdx is None:
                print("[skipped — both legs failed]")
            elif simt is None or cdx is None:
                got = (f"simt={simt:.3f}us" if simt is not None
                       else f"cublasdx={cdx:.3f}us")
                failed = "simt" if simt is None else "cublasdx"
                print(f"{got}, {failed} leg failed → SIMT default")
            else:
                if _cublasdx_wins(simt, cdx, args.margin):
                    winner = "cuBLASDx"
                elif simt < cdx * (1 - args.margin):
                    winner = "SIMT"
                else:
                    winner = "tie"
                print(f"simt={simt:.3f}us cublasdx={cdx:.3f}us → {winner}")
            api_results.append((shape, simt, cdx, simt_spread, cdx_spread))
        results_by_api[api] = api_results

    if args.dry_run:
        print("\nDry run — not writing files.")
        return

    if args.in_tree:
        # Update the in-tree file by replacing the "measured specializations"
        # section. The round-2 primary templates and footer remain intact.
        _update_in_tree(out, sms, results_by_api, args.margin, hostname)
    else:
        # Per-host override file: raw specializations consumed via
        # GLASS_TUNING_TABLE_LOCAL.
        include_path = str(out.relative_to(GLASS_DIR)) if out.is_relative_to(GLASS_DIR) else str(out)
        emit_overrides(out, sms, results_by_api, args.margin, include_path, hostname)
    emit_results_md(md, sms, results_by_api, args.margin, hostname,
                    run_provenance)

    if not args.in_tree:
        print("\nConsume the new overrides in your build with:")
        try:
            rel = out.relative_to(pathlib.Path.cwd())
            include_arg = str(rel)
        except ValueError:
            include_arg = str(out)
        print(f"  nvcc ... -DGLASS_TUNING_TABLE_LOCAL='\"{include_arg}\"' ...")


# ─── in-tree update: marker-based section replacement ──────────────────────

_IN_TREE_BEGIN = "// === BEGIN: autotune-generated specializations ==="
_IN_TREE_END   = "// === END: autotune-generated specializations ==="


def _update_in_tree(path: pathlib.Path,
                    sms: int,
                    results_by_api: dict,
                    margin: float,
                    hostname: str):
    """Replace the section bounded by the autotune markers in `path`. If the
    markers don't exist yet, insert a fresh section just before the closing
    `} // namespace _glass_tuning` (keeping round-2 primaries above it intact).
    """
    body = path.read_text()
    block_lines = [_IN_TREE_BEGIN]
    block_lines.append(f"// Generated by bench/autotune.py at "
                       f"{time.strftime('%Y-%m-%d %H:%M:%S %Z')}")
    block_lines.append(f"// Host: {hostname}    SM: sm_{sms // 10}")
    for api in API_CONFIGS:
        results = results_by_api.get(api)
        if not results:
            continue
        block_lines.append("")
        block_lines.append(f"// ─── {api} ─" + ("─" * max(0, 60 - len(api))))
        cfg = API_CONFIGS[api]
        # Sub-microsecond measurements are unreliable on small kernels
        # (timer granularity, kernel launch failures, shared-mem overflows
        # that bail before the kernel body runs all produce 0.000us-ish
        # values). Below this floor we can't trust either leg → default
        # to SIMT.
        MIN_TRUSTWORTHY_US = 0.05
        for shape, simt, cdx, _simt_spread, _cdx_spread in results:
            spec = cfg["spec_fmt"](*shape, sms)
            if simt is None or cdx is None:
                verdict, note = "false", "measurement failed → SIMT default"
            elif simt < MIN_TRUSTWORTHY_US or cdx < MIN_TRUSTWORTHY_US:
                verdict, note = "false", (
                    f"measurement below noise floor "
                    f"(simt={simt:.3f}us, cublasdx={cdx:.3f}us; "
                    f"< {MIN_TRUSTWORTHY_US:.2f}us) → SIMT default")
            else:
                ratio = cdx / simt
                if _cublasdx_wins(simt, cdx, margin):
                    verdict, note = "true", (
                        f"cublasdx wins ({cdx:.3f}us vs simt {simt:.3f}us, "
                        f"{(1-ratio)*100:.1f}%)")
                elif ratio > (1.0 + margin):
                    verdict, note = "false", (
                        f"simt wins ({simt:.3f}us vs cublasdx {cdx:.3f}us, "
                        f"{(ratio-1)*100:.1f}%)")
                else:
                    verdict, note = "false", f"tie within ±{margin*100:.0f}%"
            block_lines.append(
                f"template <> constexpr bool {spec}() {{ return {verdict}; }} // {note}")
    block_lines.append(_IN_TREE_END)
    block = "\n".join(block_lines)

    if _IN_TREE_BEGIN in body and _IN_TREE_END in body:
        # Replace the existing block in-place.
        prefix, _, rest = body.partition(_IN_TREE_BEGIN)
        _, _, suffix = rest.partition(_IN_TREE_END)
        new_body = prefix + block + suffix
    else:
        # Insert before the closing `} // namespace _glass_tuning`.
        close = "} // namespace _glass_tuning"
        if close not in body:
            sys.exit(f"ERROR: --in-tree expected '{close}' in {path}; "
                     f"file structure changed unexpectedly. Aborting.")
        prefix, _, suffix = body.partition(close)
        new_body = prefix + block + "\n\n" + close + suffix

    path.write_text(new_body)
    n_apis = sum(1 for v in results_by_api.values() if v)
    n_total = sum(len(v) for v in results_by_api.values() if v)
    print(f"\nUpdated {path} ({n_total} specializations across {n_apis} APIs, "
          f"round-2 primaries preserved).")


if __name__ == "__main__":
    main()
