#!/usr/bin/env python3
"""GLASS autotuner — measure SIMT vs cuBLASDx per (M,N,K) on this machine and
emit src/nvidia/tuning_table.cuh that glass::nvidia::should_use_cublasdx<>()
will consult at compile time.

Usage:
    python3 bench/autotune.py [--sm AUTO|<sm>]
                              [--shapes 'M1,N1,K1;M2,N2,K2;...']
                              [--iters 5000]
                              [--out src/nvidia/tuning_table.cuh]
                              [--margin 0.05]
                              [--dry-run]

Defaults:
    --sm AUTO        — detect via nvidia-smi
    --shapes         — square shapes from {3..8, 12, 14, 16, 24, 32, 48, 64}
    --iters 5000     — per-kernel timing iterations
    --margin 0.05    — within ±5% counts as a tie; ties default to SIMT
                       (cheaper compile, no DEFINE needed)
    --out PATH       — overwrite tuning_table.cuh; also writes
                       autotune_results.md alongside it for human review

Requires MATHDX_ROOT set (cuBLASDx headers needed for the cuBLASDx leg).
The shipped tuning_table.cuh always works without running this script — the
conservative shape heuristic kicks in for unmeasured shapes.
"""

import argparse
import os
import pathlib
import re
import shlex
import subprocess
import sys
import tempfile
import textwrap
import time

BENCH_DIR   = pathlib.Path(__file__).parent.resolve()
GLASS_DIR   = BENCH_DIR.parent
DEFAULT_OUT = GLASS_DIR / "src" / "nvidia" / "tuning_table.cuh"

DEFAULT_SHAPES = [
    (m, m, m) for m in (3, 4, 5, 6, 7, 8, 12, 14, 16, 24, 32, 48, 64)
]


def detect_sm() -> int:
    out = subprocess.check_output(
        ["nvidia-smi", "--query-gpu=compute_cap", "--format=csv,noheader"],
        text=True, stderr=subprocess.DEVNULL,
    ).strip().split("\n")[0].strip()
    major, minor = out.split(".")
    return int(f"{major}{minor}0")


def parse_shapes(spec: str):
    out = []
    for part in spec.split(";"):
        part = part.strip()
        if not part:
            continue
        m, n, k = (int(x) for x in part.split(","))
        out.append((m, n, k))
    return out


# ─── microbench source ────────────────────────────────────────────────────────

MICROBENCH_TEMPLATE = textwrap.dedent("""
    // Auto-generated by bench/autotune.py — measures SIMT vs cuBLASDx for one
    // (M, N, K) on the current SM. Prints two lines on stdout:
    //   simt    <us_per_op>
    //   cublasdx <us_per_op>

    #include <cstdio>
    #include <cstdlib>
    #include <ctime>
    #ifdef GLASS_BENCH_CUBLASDX
    #include <cublasdx.hpp>
    #endif
    #include "../glass-nvidia.cuh"

    static const int M = {M}, N = {N}, K = {K};
    static const int TC = 64;

    namespace glass {{ namespace nvidia {{
        DEFINE_NVIDIA_GEMM_BLOCKDIM(M, N, K, TC)
    }}}}

    __global__ void k_simt(float* A, float* B, float* C, volatile float* sink, int iters) {{
        for (int rep = 0; rep < iters; rep++) {{
            glass::gemm<float, M, N, K>(1.f, A, B, 0.f, C);
            __syncthreads();
            if (threadIdx.x == 0) sink[rep & 0xFF] = C[0];
            __syncthreads();
        }}
    }}

    __global__ void k_cublasdx(float* A, float* B, float* C, volatile float* sink, int iters) {{
        extern __shared__ __align__(16) char smem[];
        for (int rep = 0; rep < iters; rep++) {{
            glass::nvidia::gemm<float, M, N, K, TC>(1.f, A, B, 0.f, C, smem);
            __syncthreads();
            if (threadIdx.x == 0) sink[rep & 0xFF] = C[0];
            __syncthreads();
        }}
    }}

    static double elapsed_us(struct timespec a, struct timespec b) {{
        return (double)(b.tv_sec - a.tv_sec) * 1e6
             + (double)(b.tv_nsec - a.tv_nsec) * 1e-3;
    }}

    int main(int argc, char** argv) {{
        int iters = (argc > 1) ? atoi(argv[1]) : 5000;
        float *dA, *dB, *dC, *dSink;
        cudaMalloc(&dA, M*N * sizeof(float));
        cudaMalloc(&dB, N*K * sizeof(float));
        cudaMalloc(&dC, M*K * sizeof(float));
        cudaMalloc(&dSink, 256 * sizeof(float));

        struct timespec t0, t1;
        constexpr size_t smem = glass::nvidia::gemm_smem_size<float, M, N, K, TC>();

        // warmup
        k_simt<<<1, TC>>>(dA, dB, dC, dSink, 100); cudaDeviceSynchronize();
        k_cublasdx<<<1, TC, smem>>>(dA, dB, dC, dSink, 100); cudaDeviceSynchronize();

        clock_gettime(CLOCK_MONOTONIC, &t0);
        k_simt<<<1, TC>>>(dA, dB, dC, dSink, iters); cudaDeviceSynchronize();
        clock_gettime(CLOCK_MONOTONIC, &t1);
        printf("simt %.6f\\n", elapsed_us(t0, t1) / iters);

        clock_gettime(CLOCK_MONOTONIC, &t0);
        k_cublasdx<<<1, TC, smem>>>(dA, dB, dC, dSink, iters); cudaDeviceSynchronize();
        clock_gettime(CLOCK_MONOTONIC, &t1);
        printf("cublasdx %.6f\\n", elapsed_us(t0, t1) / iters);

        cudaFree(dA); cudaFree(dB); cudaFree(dC); cudaFree(dSink);
        return 0;
    }}
""").strip() + "\n"


# ─── compile + run one (M, N, K) ──────────────────────────────────────────────

def measure_shape(m, n, k, sms, iters, mathdx_root, build_dir):
    src_path = build_dir / f"_autotune_{m}x{n}x{k}.cu"
    bin_path = build_dir / f"_autotune_{m}x{n}x{k}"
    src_path.write_text(MICROBENCH_TEMPLATE.format(M=m, N=n, K=k))

    cmd = [
        "nvcc", "-std=c++17", f"-arch=sm_{sms // 10}", "-O3",
        f"-I{GLASS_DIR}", f"-I{GLASS_DIR / 'src'}",
        f"-I{mathdx_root / 'include'}",
        f"-I{mathdx_root / 'external' / 'cutlass' / 'include'}",
        "-DGLASS_BENCH_CUBLASDX", f"-DSMS={sms}",
        "--expt-relaxed-constexpr", "-Xptxas", "-O1",
        "-o", str(bin_path), str(src_path),
    ]
    res = subprocess.run(cmd, capture_output=True, text=True)
    if res.returncode != 0:
        # cuBLASDx may reject some shapes outright; treat as "SIMT wins by default".
        print(f"    [{m}x{n}x{k}] compile failed → SIMT", file=sys.stderr)
        if res.stderr:
            print(f"    nvcc stderr (first 200 chars): {res.stderr[:200]}", file=sys.stderr)
        return None, None

    res = subprocess.run([str(bin_path), str(iters)], capture_output=True, text=True)
    if res.returncode != 0:
        print(f"    [{m}x{n}x{k}] runtime failure: {res.stderr[:200]}", file=sys.stderr)
        return None, None

    simt_us = cublasdx_us = None
    for line in res.stdout.splitlines():
        m1 = re.match(r"^(simt|cublasdx)\s+([\d.]+)", line.strip())
        if not m1:
            continue
        if m1.group(1) == "simt":     simt_us = float(m1.group(2))
        else:                          cublasdx_us = float(m1.group(2))

    return simt_us, cublasdx_us


# ─── emit tuning_table.cuh ────────────────────────────────────────────────────

HEADER = '''#pragma once
#include <cstdint>

// Per-SM lookup table for `should_use_cublasdx<T,M,N,K,SM>()`. Tells
// glass::nvidia::gemm whether to dispatch to cuBLASDx (true) or fall through
// to the SIMT path (false) for a given shape on a given SM.
//
// EDITING POLICY
// --------------
// The hand-curated values below ship as defaults. To regenerate this file
// for your specific machine (recommended for production deployments — small
// shapes are quite SM-dependent), run:
//
//   python bench/autotune.py --sm AUTO --out src/nvidia/tuning_table.cuh
//
// The autotune script measures both backends for the (M,N,K) grid you
// specify, emits one explicit specialization per measured shape, and leaves
// the `cublasdx_wins<>` primary template (the conservative heuristic) as the
// fallback for unmeasured shapes.
//
// THE HEURISTIC
// -------------
// For shapes with no per-SM measurement, we use:
//   max(M,N,K) >= 16 AND min(M,N,K) >= 4
// Float-only because cuBLASDx's small-shape kernels are tuned for FP32.

namespace _glass_tuning {

// Primary template — conservative shape heuristic for unmeasured (M,N,K,SM).
template <uint32_t M, uint32_t N, uint32_t K, uint32_t SM_VAL>
constexpr bool cublasdx_wins() {
    constexpr uint32_t mx = (M > N ? (M > K ? M : K) : (N > K ? N : K));
    constexpr uint32_t mn = (M < N ? (M < K ? M : K) : (N < K ? N : K));
    return mx >= 16 && mn >= 4;
}
'''

FOOTER = "} // namespace _glass_tuning\n"


def emit_table(out_path: pathlib.Path, sms: int, results: list, margin: float):
    """Append per-SM specializations to a fresh tuning_table.cuh.

    results: list of (m, n, k, simt_us, cublasdx_us). Both timings can be None.
    """
    lines = [HEADER, ""]
    lines.append(f"// ---------------------------------------------------------------------------")
    lines.append(f"// sm_{sms // 10} — measured by bench/autotune.py at {time.strftime('%Y-%m-%d %H:%M')}.")
    lines.append(f"// ---------------------------------------------------------------------------")
    for m, n, k, simt, cdx in results:
        if simt is None or cdx is None:
            verdict = "false"
            note = " // measurement failed → SIMT default"
        else:
            ratio = cdx / simt   # < 1 means cuBLASDx is faster
            if ratio < (1.0 - margin):
                verdict = "true"
                note = f" // cublasdx wins ({cdx:.3f}us vs simt {simt:.3f}us, {(1-ratio)*100:.1f}%)"
            elif ratio > (1.0 + margin):
                verdict = "false"
                note = f" // simt wins ({simt:.3f}us vs cublasdx {cdx:.3f}us, {(ratio-1)*100:.1f}%)"
            else:
                verdict = "false"
                note = f" // tie within ±{margin*100:.0f}% → SIMT default"
        lines.append(
            f"template <> constexpr bool cublasdx_wins<{m:>2},{n:>3},{k:>3},{sms:>5}>() {{ return {verdict}; }}{note}"
        )
    lines.append("")
    lines.append(FOOTER)
    out_path.write_text("\n".join(lines))
    print(f"\nWrote {out_path} with {len(results)} measured shapes for sm_{sms // 10}.")


def emit_results_md(md_path: pathlib.Path, sms: int, results: list, margin: float):
    lines = [
        f"# autotune results — sm_{sms // 10}",
        "",
        f"_Generated by `bench/autotune.py` at {time.strftime('%Y-%m-%d %H:%M')}._",
        "",
        f"Tie tolerance: ±{margin*100:.0f}% (ties default to SIMT).",
        "",
        "| M | N | K | SIMT (us/op) | cuBLASDx (us/op) | Winner | Speedup |",
        "|---|---|---|--------------|------------------|--------|---------|",
    ]
    for m, n, k, simt, cdx in results:
        if simt is None or cdx is None:
            lines.append(f"| {m} | {n} | {k} | — | — | SIMT (compile failed) | — |")
            continue
        if cdx < simt * (1.0 - margin):
            lines.append(f"| {m} | {n} | {k} | {simt:.3f} | {cdx:.3f} | **cuBLASDx** | {simt/cdx:.2f}× |")
        elif simt < cdx * (1.0 - margin):
            lines.append(f"| {m} | {n} | {k} | {simt:.3f} | {cdx:.3f} | **SIMT** | {cdx/simt:.2f}× |")
        else:
            lines.append(f"| {m} | {n} | {k} | {simt:.3f} | {cdx:.3f} | tie (→ SIMT) | — |")
    md_path.write_text("\n".join(lines) + "\n")
    print(f"Wrote {md_path}")


# ─── main ─────────────────────────────────────────────────────────────────────

def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--sm", default="AUTO", help="SM number (e.g. 860, 1200) or AUTO")
    p.add_argument("--shapes", default=None,
                   help="Semicolon-separated 'M,N,K' tuples (default: square 3..64)")
    p.add_argument("--iters", type=int, default=10000,
                   help="Per-kernel timed iterations (default 10000). Bump for "
                        "noisy machines or for shapes hitting the tie tolerance.")
    p.add_argument("--out",  default=str(DEFAULT_OUT))
    p.add_argument("--margin", type=float, default=0.05,
                   help="Tie tolerance: |1 - cublasdx/simt| <= margin counts as a tie (default 0.05)")
    p.add_argument("--dry-run", action="store_true",
                   help="Measure but don't overwrite tuning_table.cuh")
    args = p.parse_args()

    sms = detect_sm() if args.sm == "AUTO" else int(args.sm)
    shapes = parse_shapes(args.shapes) if args.shapes else DEFAULT_SHAPES
    out = pathlib.Path(args.out).resolve()
    md  = out.with_suffix(".md").parent.joinpath(out.stem + "_results.md") \
            if False else (out.parent / (out.stem + "_results.md"))

    mathdx_root_env = os.environ.get("MATHDX_ROOT")
    if not mathdx_root_env:
        sys.exit("ERROR: MATHDX_ROOT not set — autotune needs cuBLASDx headers.")
    mathdx_root = pathlib.Path(mathdx_root_env)

    print(f"Autotune target: sm_{sms // 10} (sms={sms})")
    print(f"Shapes:          {len(shapes)} ({shapes[0]} ... {shapes[-1]})")
    print(f"Iterations:      {args.iters}")
    print(f"Tie margin:      ±{args.margin*100:.0f}%")
    print(f"MATHDX_ROOT:     {mathdx_root}")
    print(f"Output:          {out}{' (dry run)' if args.dry_run else ''}")

    with tempfile.TemporaryDirectory(prefix="glass_autotune_") as tmpdir:
        build_dir = pathlib.Path(tmpdir)
        results = []
        for m, n, k in shapes:
            print(f"  measuring {m}x{n}x{k} ...", end=" ", flush=True)
            simt, cdx = measure_shape(m, n, k, sms, args.iters, mathdx_root, build_dir)
            if simt is None or cdx is None:
                print("[skipped]")
            else:
                winner = "cuBLASDx" if cdx < simt * (1 - args.margin) else "SIMT" if simt < cdx * (1 - args.margin) else "tie"
                print(f"simt={simt:.3f}us cublasdx={cdx:.3f}us → {winner}")
            results.append((m, n, k, simt, cdx))

    if args.dry_run:
        print("\nDry run — not writing tuning_table.cuh.")
        return

    emit_table(out, sms, results, args.margin)
    emit_results_md(md, sms, results, args.margin)


if __name__ == "__main__":
    main()
